import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/sass/app.scss',
                "resources/css/app.css",
                'resources/js/app.js',
                'resources/js/pages/master-data-dashboard.js',
                'resources/js/pages/turnover.js',
                'resources/js/pages/organisasi.js',
                'resources/js/pages/departemen.js',
                'resources/js/pages/divisi.js',
                'resources/js/pages/grup.js',
                'resources/js/pages/jabatan.js',
                'resources/js/pages/karyawan.js',
                'resources/js/pages/kontrak.js',
                'resources/js/pages/posisi.js',
                'resources/js/pages/seksi.js',
                'resources/js/pages/export.js',
                'resources/js/pages/template.js',
                'resources/js/pages/event.js',
                'resources/js/pages/cutie-dashboard.js',
                'resources/js/pages/cutie-member-cuti.js',
                'resources/js/pages/cutie-pengajuan-cuti.js',
                'resources/js/pages/cutie-personalia-cuti.js',
                'resources/js/pages/cutie-export.js',
                'resources/js/pages/cutie-setting.js',
                'resources/js/pages/cutie-bypass-cuti.js',
                'resources/js/pages/menu.js',
                'resources/js/pages/lembure-pengajuan-lembur.js',
                'resources/js/pages/lembure-approval-lembur.js',
                'resources/js/pages/lembure-detail-lembur.js',
                'resources/js/pages/lembure-setting-upah-lembur.js',
                'resources/js/pages/lembure-setting-lembur.js',
                'resources/js/pages/lembure-dashboard.js',
                'resources/js/pages/lembure-setting-gaji-departemen.js',
                'resources/js/pages/izine-pengajuan-izin.js',
                'resources/js/pages/izine-lapor-skd.js',
                'resources/js/pages/izine-approval-izin.js',
                'resources/js/pages/izine-approval-skd.js',
                'resources/js/pages/izine-log-book-izin.js',
            ],
            // refresh: true,
            refresh: ["resources/views/**", "resources/css/**", "app/Http/**"],
        }),
    ],
});
